set shell=/bin/sh         " fix for fish

source ~/.vim/plugins.vim " load plugins

set noswapfile            " do not use swap files
set autoread              " reload file if changed outside
set autowrite             " automatically save before commands like :next and :make
set hidden                " allow hiding a buffer with unsaved changes
set encoding=utf-8        " set file encoding

set tabstop=4             " set hard tab size
set softtabstop=2         " set soft tab size
set shiftwidth=2          " set autoindent size
set expandtab             " use soft tabs

set wildmenu              " show list of matching items when tab completing
set number                " show line numbers
set cursorline            " highlight current line
set wrap                  " wrap lines
set laststatus=2          " show the status bar
set history=999           " set command history size
set visualbell t_vb=      " no bell

set ignorecase            " searches are case insensitive...
set smartcase             " ...unless they contain any capital letters
set incsearch             " set incremental searching
set hlsearch              " highlight search results

syntax enable             " enable syntax highlighting
colorscheme solarized     " set colorscheme
set background=light      " set background color

set backspace=indent,eol,start  " backspace through everything in insert mode
set whichwrap+=<,>,h,l          " navigate through line wraps

" lines at columns 81 (unix standard)
" and 121 (github-safe)
let &colorcolumn="81,121"

" map the arrow keys to be based on display lines, not physical lines
map <Down> gj
map <Up> gk
nnoremap j gj
nnoremap k gk

" show tabs and trailing whitespace with special characters
set list listchars=tab:▸\ ,trail:·

nmap <silent> <C-n> :cn<cr>   " move to next file in quickfix list
nmap <silent> <C-p> :cp<cr>   " move to previous file in quickfix list

let mapleader = ','           " set <leader> key

" cycle through open buffers with tab and shift-tab
nnoremap <tab> :bnext<cr>
nnoremap <s-tab> :bprevious<cr>

source ~/.vim/configs.vim     " load plugin configurations
source ~/.vim/functions.vim   " load custom functions

" close current buffer and go to previous
nnoremap <leader>d :bprevious <bar> :bd#<CR>

" toggle search highlighting
noremap <leader><space> :set hlsearch! hlsearch?<cr>

" toggle paste mode
map <leader>p :setlocal paste!<cr>
